# Generated by Django 4.2.23 on 2025-08-01 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(default=None, null=True)),
                ('education', models.CharField(choices=[('None', '無'), ('ES', '小學'), ('MS', '初中'), ('HS', '高中'), ('BA', '大學'), ('MA', '碩士'), ('PhD', '博士')], default=None, max_length=10, null=True)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
