# Generated by Django 4.2.23 on 2025-08-06 03:43
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS unique_email_idx;
                CREATE UNIQUE INDEX unique_email_idx ON auth_user(email);
            """,
            reverse_sql="DROP INDEX IF EXISTS unique_email_idx;",
        ),
    ]
