# Generated by Django 4.2.23 on 2025-08-15 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_public_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
    ]
